/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-07-14 11:32:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.auth;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LogInForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<style>\r\n");
      out.write("@import url(http://weloveiconfonts.com/api/?family=fontawesome);\r\n");
      out.write("@import url(http://fonts.googleapis.com/css?family=Open+Sans:400,700);\r\n");
      out.write("\r\n");
      out.write("[class*=\"fontawesome-\"]:before {font-family: 'FontAwesome', sans-serif;}\r\n");
      out.write("\r\n");
      out.write("* {\tbox-sizing: border-box;}\r\n");
      out.write("\r\n");
      out.write("html {height: 100%;}\r\n");
      out.write("\r\n");
      out.write("body {background-color: #eee; color: #606468; font: 400 0.875rem/1.5 \"Open Sans\", sans-serif; margin: 0;min-height: 100%;}\r\n");
      out.write("a {color: #eee;outline: 0;text-decoration: none;}\r\n");
      out.write("a:focus, a:hover {text-decoration: underline;}\r\n");
      out.write("input { border: 0; color: inherit; font: inherit; margin: 0; outline: 0; padding: 0; -webkit-transition: background-color .3s; transition: background-color .3s;}\r\n");
      out.write(".site__container {-webkit-box-flex: 1;-webkit-flex: 1;-ms-flex: 1;flex: 1;padding: 3rem 0;}\r\n");
      out.write(".form input[type=\"password\"], .form input[type=\"text\"], .form input[type=\"submit\"]{width:100%;}\r\n");
      out.write(".form--login {color: #606468;}\r\n");
      out.write(".form--login label, .form--login input[type=\"text\"], .form--login input[type=\"password\"],\r\n");
      out.write(".form--login input[type=\"submit\"] {border-radius: 0.25rem;padding: 1rem;}\r\n");
      out.write(".form--login label {background-color: #363b41;border-bottom-right-radius: 0;border-top-right-radius: 0;padding-left: 1.25rem;padding-right: 1.25rem;}\r\n");
      out.write(".form--login input[type=\"text\"], .form--login input[type=\"password\"] {border-bottom-left-radius: 0;border-top-left-radius: 0;}\r\n");
      out.write(".form--login input[type=\"submit\"] {background-color: #3f8ca6;color: #eee;font-weight: bold;\ttext-transform: uppercase;}\r\n");
      out.write(".form--login input[type=\"submit\"]:focus, .form--login input[type=\"submit\"]:hover{background-color: #3f8ca6;}\r\n");
      out.write(".form__field {display: -webkit-box;\tdisplay: -webkit-flex;\tdisplay: -ms-flexbox;\tdisplay: flex;\tmargin-bottom: 1rem;}\r\n");
      out.write(".form__input {\t-webkit-box-flex: 1;\t-webkit-flex: 1;\t-ms-flex: 1;\tflex:a 1;}\r\n");
      out.write(".align {-webkit-box-align: center;-webkit-align-items: center;-ms-flex-align: center;align-items: center;display: -webkit-box;display: -webkit-flex;\r\n");
      out.write("\tdisplay: -ms-flexbox;display: flex;-webkit-box-orient: horizontal;-webkit-box-direction: normal;-webkit-flex-direction: row;-ms-flex-direction: row;\r\n");
      out.write("\tflex-direction: row;}\r\n");
      out.write(".hidden {border: 0;\tclip: rect(0, 0, 0, 0);\theight: 1px;\tmargin: -1px;\toverflow: hidden;\tpadding: 0;\tposition: absolute;\twidth: 1px;}\r\n");
      out.write(".text--center {\ttext-align: center;}\r\n");
      out.write(".grid__container {\tmargin: 0 auto;\tmax-width: 20rem;\twidth: 90%;}\r\n");
      out.write("</style>\r\n");
      out.write("<title>로그인</title>\r\n");
      out.write("<script>\r\n");
      out.write("\t\tfunction login(){\r\n");
      out.write("\t\talert(\"로그인에 성공하셨습니다\");\r\n");
      out.write("\t\twindow.open(\"http://localhost:9999/_bus_project/search/searchFromLogOut.jsp\", \"_self\");\t\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"align\">\r\n");
      out.write("<div class=\"site__container\">\r\n");
      out.write("    <div class=\"grid__container\">\r\n");
      out.write("      <form action=\"login.do\" method=\"post\" class=\"form form--login\">\r\n");
      out.write("        <div class=\"form__field\">\r\n");
      out.write("          <label class=\"fontawesome-user\" for=\"login__username\"><span class=\"hidden\">Username</span></label>\r\n");
      out.write("          <input id=\"login__username\" type=\"text\" class=\"form__input\" placeholder=\"Username\" name=\"email\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bus.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form__field\">\r\n");
      out.write("          <label class=\"fontawesome-lock\" for=\"login__password\"><span class=\"hidden\">Password</span></label>\r\n");
      out.write("          <input id=\"login__password\" type=\"password\" class=\"form__input\" placeholder=\"Password\" name=\"password\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bus.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form__field\">\r\n");
      out.write("          <input type=\"submit\" value=\"로그인\" style=\"cursor:pointer\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
