/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-07-15 08:33:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.auth;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.sun.xml.internal.txw2.Document;
import java.io.PrintWriter;
import spms.controls.ManagerUpdateController;
import spms.controls.*;

public final class MemberForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Lecture/4thProject(BusProject)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/_bus_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1586138553000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("spms.controls");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("com.sun.xml.internal.txw2.Document");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("spms.controls.ManagerUpdateController");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원 가입 페이지</title>\r\n");
      out.write("<script>\r\n");
      out.write("    function selfClose(){\r\n");
      out.write("        self.close();\r\n");
      out.write("    }\r\n");
      out.write("    function joinOK(){\r\n");
      out.write("        alert(\"회원가입을 축하드립니다.\")\r\n");
      out.write("        $(\"#form\").submit()\r\n");
      out.write("        self.close();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("@import url(http://weloveiconfonts.com/api/?family=fontawesome);\r\n");
      out.write("@import url(http://fonts.googleapis.com/css?family=Open+Sans:400,700);\r\n");
      out.write("[class*=\"fontawesome-\"]:before {font-family: 'FontAwesome', sans-serif;}\r\n");
      out.write("\r\n");
      out.write("* {box-sizing: border-box;}\r\n");
      out.write("\r\n");
      out.write("html {height: 100%;}\r\n");
      out.write("\r\n");
      out.write("body {background-color: #eee;\r\n");
      out.write("  color: #606468;\r\n");
      out.write("  font: 400 0.875rem/1.5 \"Open Sans\", sans-serif;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  min-height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("  color: #eee;\r\n");
      out.write("  outline: 0;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:focus, a:hover {text-decoration: underline;}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("  border: 0;\r\n");
      out.write("  color: inherit;\r\n");
      out.write("  font: inherit;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  outline: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  -webkit-transition: background-color .3s;\r\n");
      out.write("          transition: background-color .3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".site__container {\r\n");
      out.write("  -webkit-box-flex: 1;\r\n");
      out.write("  -webkit-flex: 1;\r\n");
      out.write("      -ms-flex: 1;\r\n");
      out.write("          flex: 1;\r\n");
      out.write("  padding: 3rem 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form input[type=\"password\"], .form input[type=\"text\"]{width: 100%;}\r\n");
      out.write(".form input[type=\"button\"], .form input[type=\"reset\"] {width: 50%;}\r\n");
      out.write("\r\n");
      out.write(".form--login {color: #606468;}\r\n");
      out.write(".form--login label,\r\n");
      out.write(".form--login input[type=\"text\"],\r\n");
      out.write(".form--login input[type=\"reset\"],\r\n");
      out.write(".form--login input[type=\"password\"],\r\n");
      out.write(".form--login input[type=\"button\"] {\r\n");
      out.write("  border-radius: 0.25rem;\r\n");
      out.write("  padding: 1rem;\r\n");
      out.write("}\r\n");
      out.write(".form--login label {\r\n");
      out.write("  background-color: #363b41;\r\n");
      out.write("  border-bottom-right-radius: 0;\r\n");
      out.write("  border-top-right-radius: 0;\r\n");
      out.write("  padding-left: 1.25rem;\r\n");
      out.write("  padding-right: 1.25rem;\r\n");
      out.write("}\r\n");
      out.write(".form--login .fontawesome-lock {\r\n");
      out.write("  padding-left: 1.4rem;\r\n");
      out.write("  padding-right: 1.4rem;\r\n");
      out.write("}\r\n");
      out.write(".form--login .fontawesome-user {\r\n");
      out.write("  padding-left: 1.35rem;\r\n");
      out.write("  padding-right: 1.35rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".form--login input[type=\"text\"], .form--login input[type=\"password\"] {\r\n");
      out.write("  border-bottom-left-radius: 0;\r\n");
      out.write("  border-top-left-radius: 0;\r\n");
      out.write("}\r\n");
      out.write(".form--login input[type=\"button\"] {\r\n");
      out.write("  background-color: #3f8ca6;\r\n");
      out.write("  color: #eee;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write(".form--login input[type=\"button\"]:focus, .form--login input[type=\"button\"]:hover {\r\n");
      out.write("  background-color: #3f8ca6;\r\n");
      out.write("}\r\n");
      out.write(".form--login input[type=\"reset\"] {\r\n");
      out.write("  background-color: #3f8ca6;\r\n");
      out.write("  color: #eee;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write(".form--login input[type=\"reset\"]:focus, .form--login input[type=\"reset\"]:hover {\r\n");
      out.write("  background-color: #3f8ca6;\r\n");
      out.write("}\r\n");
      out.write(".form__field {\r\n");
      out.write("  display: -webkit-box;\r\n");
      out.write("  display: -webkit-flex;\r\n");
      out.write("  display: -ms-flexbox;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write(".form__field .first{\r\n");
      out.write("    margin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write(".form__input {\r\n");
      out.write("  -webkit-box-flex: 1;\r\n");
      out.write("  -webkit-flex: 1;\r\n");
      out.write("      -ms-flex: 1;\r\n");
      out.write("          flex: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".align {\r\n");
      out.write("  -webkit-box-align: center;\r\n");
      out.write("  -webkit-align-items: center;\r\n");
      out.write("      -ms-flex-align: center;\r\n");
      out.write("          align-items: center;\r\n");
      out.write("  display: -webkit-box;\r\n");
      out.write("  display: -webkit-flex;\r\n");
      out.write("  display: -ms-flexbox;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  -webkit-box-orient: horizontal;\r\n");
      out.write("  -webkit-box-direction: normal;\r\n");
      out.write("  -webkit-flex-direction: row;\r\n");
      out.write("      -ms-flex-direction: row;\r\n");
      out.write("          flex-direction: row;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hidden {\r\n");
      out.write("  border: 0;\r\n");
      out.write("  clip: rect(0 0 0 0);\r\n");
      out.write("  height: 1px;\r\n");
      out.write("  margin: -1px;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text--center {text-align: center;}\r\n");
      out.write("\r\n");
      out.write(".grid__container {margin: 0 auto; max-width: 20rem; width: 90%;}\r\n");
      out.write("\r\n");
      out.write(".submit_cursor{cursor:pointer}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"align\">\r\n");
      out.write("  <div class=\"site__container\">\r\n");
      out.write("    <div class=\"grid__container\">\r\n");
      out.write("      <form action=\"add.do\" method=\"post\" class=\"form form--login\" id=\"form\">\r\n");
      out.write("        <div class=\"form__field\">\r\n");
      out.write("          <label class=\"fontawesome-envelope-alt\" for=\"login__email\"><span class=\"hidden\">E-mail</span></label>\r\n");
      out.write("          <input  type=\"text\" placeholder=\"E-mail\" name=\"email\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form__field\">\r\n");
      out.write("          <label class=\"fontawesome-lock\" for=\"login__password\"><span class=\"hidden\">Password</span></label>\r\n");
      out.write("          <input type=\"password\" placeholder=\"Password\" name=\"password\">\r\n");
      out.write("        </div>  \r\n");
      out.write("        <div class=\"form__field\">\r\n");
      out.write("            <label class=\"fontawesome-user\" for=\"login__username\"><span class=\"hidden\">Username</span></label>\r\n");
      out.write("            <input type=\"text\"  placeholder=\"Username\" name=\"bname\">\r\n");
      out.write("          </div>\r\n");
      out.write("        <div class=\"form__field\">\r\n");
      out.write("          <input type=\"button\" value=\"회원가입\" class=\"submit_cursor first\" onclick='joinOK()'>\r\n");
      out.write("          <input type=\"reset\" value=\"취소\" class=\"submit_cursor\" onclick='selfClose()'>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
