/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-07-15 08:29:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.auth;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Lecture/4thProject(BusProject)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/_bus_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1586138553000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원 정보</title>\r\n");
      out.write("<style>\r\n");
      out.write("     .content{width:1000px;margin: 40px auto 0;}\r\n");
      out.write("    h1{margin: 0 auto; font-size:25px; margin-bottom: 5px;text-align: left;}\r\n");
      out.write("    .table{border-spacing: 0; margin-bottom:30px;}\r\n");
      out.write("    .table th{background-color: #fbfbfb;padding: 10px 10px; border-bottom:1px solid #e7e7e7; width: 100px;}\r\n");
      out.write("    .table td{ border-bottom:1px solid #e7e7e7;padding:0px 0px 0px 20px;}\r\n");
      out.write("    .table #first{border-top:2px solid #e5e5e5;}\r\n");
      out.write("    .table #last{border-bottom:2px solid #e5e5e5;}\r\n");
      out.write("    .input{width:300px;text-align: center;border:none; border-right:0px; border-top:0px; border-left:0px; border-bottom:0px;}\r\n");
      out.write("    .no-border{border:0px;}\r\n");
      out.write("    input:focus{outline: none;}\r\n");
      out.write("    .table {margin: 0 auto;border-collapse: collapse;border-top: 3px solid #168;width: 1000px;}  \r\n");
      out.write("    .table th {color: #168;background: #f0f6f9;text-align: center;}\r\n");
      out.write("    .table th, .table td {padding: 10px;border: 1px solid #ddd;}\r\n");
      out.write("    .table th:first-child, .table td:first-child {border-left: 0;}\r\n");
      out.write("    .table th:last-child, .table td:last-child {border-right: 0;}\r\n");
      out.write("    .table tr td:first-child{text-align: center;}\r\n");
      out.write("    .table caption{caption-side: bottom; display: none;}\r\n");
      out.write("    #table_bottom{\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    /*조회*/\r\n");
      out.write(".dropdown {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  height: 28px;\r\n");
      out.write("  width: 150px;\r\n");
      out.write("  background: #f2f2f2;\r\n");
      out.write("  border: 1px solid;\r\n");
      out.write("  border-color: white #f7f7f7 #f5f5f5;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("  background-image: -webkit-linear-gradient(top, transparent, rgba(0, 0, 0, 0.06));\r\n");
      out.write("  background-image: -moz-linear-gradient(top, transparent, rgba(0, 0, 0, 0.06));\r\n");
      out.write("  background-image: -o-linear-gradient(top, transparent, rgba(0, 0, 0, 0.06));\r\n");
      out.write("  background-image: linear-gradient(to bottom, transparent, rgba(0, 0, 0, 0.06));\r\n");
      out.write("  -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.08);\r\n");
      out.write("  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.08);\r\n");
      out.write("}\r\n");
      out.write(".dropdown2 {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropbutton {\r\n");
      out.write("    height: 28px;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  background: #317d97;\r\n");
      out.write("  border: 1px solid;\r\n");
      out.write("  border-color: white #f7f7f7 #f5f5f5;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("  background-image: -webkit-linear-gradient(top, transparent, rgba(0, 0, 0, 0.06));\r\n");
      out.write("  background-image: -moz-linear-gradient(top, transparent, rgba(0, 0, 0, 0.06));\r\n");
      out.write("  background-image: -o-linear-gradient(top, transparent, rgba(0, 0, 0, 0.06));\r\n");
      out.write("  background-image: linear-gradient(to bottom, transparent, rgba(0, 0, 0, 0.06));\r\n");
      out.write("  -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.08);\r\n");
      out.write("  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.08);\r\n");
      out.write("  color:white;}\r\n");
      out.write(".dropdown-input {display: inline-block;position: relative;overflow: hidden; height: 28px;\r\n");
      out.write("  width: 150px; background: #f2f2f2; border: 1px solid; border-color: white #f7f7f7 #f5f5f5; border-radius: 3px;\r\n");
      out.write("  background-image: -webkit-linear-gradient(top, transparent, rgba(0, 0, 0, 0.06));  background-image: -moz-linear-gradient(top, transparent, rgba(0, 0, 0, 0.06));\r\n");
      out.write("  background-image: -o-linear-gradient(top, transparent, rgba(0, 0, 0, 0.06));  background-image: linear-gradient(to bottom, transparent, rgba(0, 0, 0, 0.06));\r\n");
      out.write("  -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.08);  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.08);}\r\n");
      out.write(".dropdown:before, .dropdown:after {content: ''; position: absolute; z-index: 2; top: 9px;  right: 10px; width: 0; height: 0; border: 4px dashed; border-color: #888 transparent;\r\n");
      out.write("  pointer-events: none;}\r\n");
      out.write(".dropdown:before { border-bottom-style: solid; border-top: none;}\r\n");
      out.write(".dropdown:after { margin-top: 7px; border-top-style: solid; border-bottom: none;}\r\n");
      out.write(".dropdown-select { position: relative; width: 130%; margin: 0; padding: 6px 8px 6px 10px; height: 28px; line-height: 14px; font-size: 12px; color: #62717a;\r\n");
      out.write("  text-shadow: 0 1px white; background: #f2f2f2; background: rgba(0, 0, 0, 0) !important; border: 0; border-radius: 0; -webkit-appearance: none;}\r\n");
      out.write(".dropdown-select:focus { z-index: 3;  width: 100%; color: #394349; outline: none; outline-offset: -2px;}\r\n");
      out.write(".dropdown-select > option { margin: 3px; padding: 6px 8px; text-shadow: none; background: #f2f2f2; border-radius: 3px; cursor: pointer;}\r\n");
      out.write(".lt-ie9 .dropdown { z-index: 1;}\r\n");
      out.write(".lt-ie9 .dropdown-select {z-index: -1;}\r\n");
      out.write(".lt-ie9 .dropdown-select:focus { z-index: 3;}\r\n");
      out.write("@-moz-document url-prefix() { .dropdown-select { padding-left: 6px; }}\r\n");
      out.write(".dropdown2 { display: inline-block; position: relative; overflow: hidden;}\r\n");
      out.write(".dropbutton {height: 28px; width: 50px;background: #317d97;border: 1px solid; border-color: white #f7f7f7 #f5f5f5; border-radius: 3px;  background-image: -webkit-linear-gradient(top, transparent, rgba(0, 0, 0, 0.06));\r\n");
      out.write("  background-image: -moz-linear-gradient(top, transparent, rgba(0, 0, 0, 0.06));  background-image: -o-linear-gradient(top, transparent, rgba(0, 0, 0, 0.06));\r\n");
      out.write("  background-image: linear-gradient(to bottom, transparent, rgba(0, 0, 0, 0.06));  -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.08);  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.08);  color:white;}\r\n");
      out.write(".in-logo{   font-size: 26px; margin-right: 15px;vertical-align: middle;}\r\n");
      out.write(".vertical{vertical-align: top; padding-right: 2px;}\r\n");
      out.write(".text{ margin: 0px 0px 7px 0px; font-size:13px; color: #666;}\r\n");
      out.write("#mg_top{margin-top: 15px;}\r\n");
      out.write(".arrive{text-align: center;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("  \t <h1><span class=\"in_logo\"><img src=\"logo.png\" class=\"vertical\"></span>회원정보</h1>\r\n");
      out.write("    <form method='get'>\r\n");
      out.write("    <table class=\"table\" id=\"table_bottom\">\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>이메일</th>\r\n");
      out.write("            <td><input type='text' name='email' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bus.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class=\"no-border\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th id=\"last\">이름</th>\r\n");
      out.write("            <td id=\"last\"><input type='text' name='name' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bus.bname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' class=\"no-border\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    </form>\r\n");
      out.write("\t\r\n");
      out.write("\t<p class=\"text\">ㆍ버스번호를 선택해주세요</p>\r\n");
      out.write("\t<form action=\"searchMypage.do\" method=\"post\">\r\n");
      out.write("\t  <div class=\"dropdown\">\r\n");
      out.write("\t\t\t<select name=\"busNo\" id=\"busNo\" class=\"dropdown-select\">\r\n");
      out.write("\t\t\t\t<option value=\"\">버스번호</option>\r\n");
      out.write("\t\t\t\t<option value=\"1001\">1001</option>\r\n");
      out.write("\t\t\t\t<option value=\"1002\">1002</option>\r\n");
      out.write("\t\t\t\t<option value=\"1003\">1003</option>\r\n");
      out.write("\t\t\t\t<option value=\"1004\">1004</option>\r\n");
      out.write("\t\t\t\t<option value=\"1005\">1005</option>\r\n");
      out.write("\t\t\t\t<option value=\"1006\">1006</option>\r\n");
      out.write("\t\t\t\t<option value=\"1007\">1007</option>\r\n");
      out.write("\t\t\t\t<option value=\"1008\">1008</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("               <div class=\"dropdown2\">\r\n");
      out.write("            <button type=\"submit\" class=\"dropbutton\" >조회</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\t</form>\r\n");
      out.write("           <h1 id=\"mg_top\"><span class=\"in_logo\"><img src=\"logo.png\" class=\"vertical\"></span>운행 리스트</h1>\r\n");
      out.write("\t<table class=\"table\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>출발일</th>\r\n");
      out.write("\t\t\t<th>출발지-도착지</th>\r\n");
      out.write("\t\t\t<th>출발시간</th>\r\n");
      out.write("\t\t\t<th>도착시간</th>\r\n");
      out.write("\t\t\t<th>버스번호</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /auth/myPage.jsp(141,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      // /auth/myPage.jsp(141,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/auth/myPage.jsp(141,2) '${test}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${test}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t<tr>\r\n");
            out.write("\t\t\t\t<td class=\"arrive\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.departureDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td class=\"arrive\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.departure}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" ▶   ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.arrive}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td class=\"arrive\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.departureTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td class=\"arrive\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.arriveTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td class=\"arrive\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.busNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
